reviews:
  auto_review:
    enabled: true

    # Allow reviews on both default and non-default branches
    base_branches:
      - main
      - dev

  path_filters:
    - "**/*.py"
    - "**/pyproject.toml"
    - "**/setup.py"
    - "**/setup.cfg"
    - "**/requirements*.txt"
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.md"
    - "**/Dockerfile"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!**/*.pyo"
    - "!**/*.pyd"
    - "!**/.pytest_cache/**"
    - "!**/.venv/**"
    - "!**/venv/**"
    - "!**/env/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/*.egg-info/**"
    - "!**/*.log"
    - "!**/.tox/**"
    - "!**/node_modules/**"
